version: '3.7'

services:
    # Spring 애플리케이션
    spring-app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - opentelemetry-collector
        networks:
            - economeans
        environment:
            OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector:4317"
            OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
            OTEL_EXPORTER_OTLP_INSECURE: "true"
        env_file:
            .env
    opentelemetry-collector:
        image: otel/opentelemetry-collector-contrib:latest
        container_name: opentelemetry-collector
        volumes:
            - ./config/collector/config.yml/:/etc/opentelemetry-collector.yml
        command:
            - "--config=/etc/opentelemetry-collector.yml"
        networks:
            - economeans
        ports:
            - 4317:4317
networks:
    economeans:
